=== S-100ExpertTeam/OpenS100/ProgramData/PC/S129_Portrayal/ColorProfiles/s100ColorProfile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="Token">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:pattern value="[a-zA-Z][0-9a-zA-Z_]*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ColorInteger">
    <xs:restriction base="xs:nonNegativeInteger">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="255"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NormalDouble">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="0.0"/>
      <xs:maxInclusive value="1.0"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="CIExyL">
    <xs:sequence>
      <xs:element name="x" type="NormalDouble"/>
      <xs:element name="y" type="NormalDouble"/>
      <xs:element name="L" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CIEXYZ">
    <xs:sequence>
      <xs:element name="X" type="xs:double"/>
      <xs:element name="Y" type="xs:double"/>
      <xs:element name="Z" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="sRGB">
    <xs:sequence>
      <xs:element name="red" type="ColorInteger"/>
      <xs:element name="green" type="ColorInteger"/>
      <xs:element name="blue" type="ColorInteger"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CIE">
    <xs:choice>
      <xs:element name="xyL" type="CIExyL"/>
      <xs:element name="XYZ" type="CIEXYZ"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="ColorName">
    <xs:sequence>
      <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="token" type="Token" use="required"/>
  </xs:complexType>
  <xs:complexType name="Colors">
    <xs:sequence>
      <xs:element name="color" type="ColorName" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PaletteItem">
    <xs:sequence>
      <xs:element name="cie" type="CIE"/>
      <xs:element name="srgb" type="SRGB"/>
    </xs:sequence>
    <xs:attribute name="token" type="Token" use="required"/>
  </xs:complexType>
  <xs:complexType name="Palette">
    <xs:sequence>
      <xs:element name="item" type="PaletteItem" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="ColorProfile">
    <xs:sequence>
      <xs:element name="colors" type="Colors">
        <xs:key name="colorKey">
          <xs:selector xpath="color"/>
          <xs:field xpath="@token"/>
        </xs:key>
      </xs:element>
      <xs:element name="palette" type="Palette" minOccurs="1" maxOccurs="unbounded">
        <xs:unique name="tokenUnique">
          <xs:selector xpath="item"/>
          <xs:field xpath="@token"/>
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="colorProfile" type="ColorProfile">
    <xs:keyref name="colorRef" refer="colorKey">
      <xs:selector xpath="palette/item"/>
      <xs:field xpath="@token"/>
    </xs:keyref>
  </xs:element>
</xs:schema>

=== S-100ExpertTeam/OpenS100/ProgramData/PC/S421_Portrayal/ColorProfiles/s100SampleColorProfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<colorProfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="s100ColorProfile.xsd">
<colors>
	<color token="NODTA" name="grey">
	<description>No data color</description>
	</color>
	<color token="CURSR" name="orange"/>
</colors>
<palette name="Day">
	<item token="NODTA">
		<cie>
			<xyL>
			<x>0.280</x>
			<y>0.310</y>
			<L>45.0</L>
			</xyL>
		</cie>
		<srgb>
			<red>171</red>
			<green>192</green>
			<blue>177</blue>
		</srgb>
	</item>
	<item token="CURSR">
		<cie>
			<xyL>
			<x>0.52</x>
			<y>0.39</y>
			<L>28.0</L>
			</xyL>
		</cie>
		<srgb>
			<red>230</red>
			<green>121</green>
			<blue>56</blue>
		</srgb>
	</item>
</palette>
<palette name="Dusk">
	<item token="NODTA">
		<cie>
			<xyL>
			<x>0.28</x>
			<y>0.31</y>
			<L>25.0</L>
			</xyL>
		</cie>
			<srgb>
			<red>136</red>
			<green>152</green>
			<blue>139</blue>
		</srgb>
	</item>
	<item token="CURSR">
		<cie>
			<xyL>
			<x>0.52</x>
			<y>0.39</y>
			<L>28.0</L>
		</xyL>
		</cie>
			<srgb>
			<red>230</red>
			<green>121</green>
			<blue>56</blue>
		</srgb>
	</item>
</palette>
<palette name="Night">
	<item token="NODTA">
		<cie>
			<xyL>
			<x>0.28</x>
			<y>0.31</y>
			<L>2.25</L>
			</xyL>
		</cie>
		<srgb>
			<red>56</red>
			<green>61</green>
			<blue>55</blue>
		</srgb>
	</item>
	<item token="CURSR">
		<cie>
			<xyL>
			<x>0.52</x>
			<y>0.39</y>
			<L>2.52</L>
			</xyL>
		</cie>
			<srgb>
			<red>89</red>
			<green>50</green>
			<blue>22</blue>
		</srgb>
	</item>
</palette>
</colorProfile>

=== S-100ExpertTeam/OpenS100/ProgramData/PC/S129_Portrayal/ColorProfiles/colorProfile.xml
<?xml version="1.0" encoding="utf-8"?>
<cp:colorProfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cp="http://www.iho.int/S100ColorProfile/5.1" xsi:schemaLocation="http://www.iho.int/S100ColorProfile/5.1 https://schemas.s100dev.net/schemas/S100/5.1.0/S100PC/20230327/S100ColorProfile.xsd">
	<colors>
		<color token="GOLDN" name="gold">
			<description>Golden color for Almost Non Navigable Area</description>
		</color>
		<color token="RED" name="red">
			<description>Red color for Non Navigable Area</description>
		</color>
		<color token="BLK" name="black">
			<description>Black color for only Text</description>
		</color>
		<color token="WHITE" name="white">
			<description>White color for Text with background</description>
		</color>
		<color token="CHMGD" name="magenta">
			<description>Chart magenta dominant</description>
		</color>
		<color token="SNDG2" name="black">
			<description>Sounding shallow</description>
		</color>
		<color token="PLRTE" name="red">
			<description>Planned route</description>
		</color>
		<color token="ORG" name="orange">
			<description>Orange color</description>
		</color>
		<color token="DEPCN" name="grey">
			<description>depth contour</description>
		</color>
	</colors>
	<palette name="Day" css="daySvgStyle.css">
		<item token="ORG">
			<cie>
				<xyL>
					<x>0.5</x>
					<y>0.4</y>
					<L>32</L>
				</xyL>
			</cie>
			<srgb>
				<red>227</red>
				<green>128</green>
				<blue>57</blue>
			</srgb>
		</item>
		<item token="RED">
			<cie>
				<xyL>
					<x>0.48</x>
					<y>0.30</y>
					<L>25</L>
				</xyL>
			</cie>
			<srgb>
				<red>234</red>
				<green>84</green>
				<blue>113</blue>
			</srgb>
		</item>
		<item token="BLK">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.31</y>
					<L>0</L>
				</xyL>
			</cie>
			<srgb>
				<red>0</red>
				<green>0</green>
				<blue>0</blue>
			</srgb>
		</item>
		<item token="WHITE">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.31</y>
					<L>80</L>
				</xyL>
			</cie>
			<srgb>
				<red>201</red>
				<green>237</green>
				<blue>255</blue>
			</srgb>
		</item>
		<item token="CHMGD">
			<cie>
				<xyL>
					<x>0.3</x>
					<y>0.17</y>
					<L>20</L>
				</xyL>
			</cie>
			<srgb>
				<red>192</red>
				<green>69</green>
				<blue>209</blue>
			</srgb>
		</item>
		<item token="SNDG2">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.31</y>
					<L>0</L>
				</xyL>
			</cie>
			<srgb>
				<red>0</red>
				<green>0</green>
				<blue>0</blue>
			</srgb>
		</item>
		<item token="GOLDN">
			<cie>
				<xyL>
					<x>0.45</x>
					<y>0.48</y>
					<L>70</L>
				</xyL>
			</cie>
			<srgb>
				<red>255</red>
				<green>215</green>
				<blue>0</blue>
			</srgb>
		</item>
		<item token="PLRTE">
			<cie>
				<xyL>
					<x>0.58</x>
					<y>0.35</y>
					<L>18</L>
				</xyL>
			</cie>
			<srgb>
				<red>214</red>
				<green>63</green>
				<blue>36</blue>
			</srgb>
		</item>
		<item token="DEPCN" transparency="1.0">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.31</y>
					<L>25</L>
				</xyL>
			</cie>
			<srgb>
				<red>118</red>
				<green>140</green>
				<blue>151</blue>
			</srgb>
		</item>
	</palette>
	<palette name="Dusk" css="duskSvgStyle.css">
		<item token="ORG">
			<cie>
				<xyL>
					<x>0.5</x>
					<y>0.4</y>
					<L>10</L>
				</xyL>
			</cie>
			<srgb>
				<red>134</red>
				<green>73</green>
				<blue>30</blue>
			</srgb>
		</item>
		<item token="RED">
			<cie>
				<xyL>
					<x>0.48</x>
					<y>0.3</y>
					<L>10</L>
				</xyL>
			</cie>
			<srgb>
				<red>155</red>
				<green>53</green>
				<blue>73</blue>
			</srgb>
		</item>
		<item token="BLK">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.31</y>
					<L>20</L>
				</xyL>
			</cie>
			<srgb>
				<red>107</red>
				<green>127</green>
				<blue>137</blue>
			</srgb>
		</item>
		<item token="WHITE">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.31</y>
					<L>36</L>
				</xyL>
			</cie>
			<srgb>
				<red>140</red>
				<green>166</green>
				<blue>179</blue>
			</srgb>
		</item>
		<item token="CHMGD">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.24</y>
					<L>18</L>
				</xyL>
			</cie>
			<srgb>
				<red>130</red>
				<green>108</green>
				<blue>161</blue>
			</srgb>
		</item>
		<item token="SNDG2">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.31</y>
					<L>36</L>
				</xyL>
			</cie>
			<srgb>
				<red>140</red>
				<green>166</green>
				<blue>179</blue>
			</srgb>
		</item>
		<item token="GOLDN">
			<cie>
				<xyL>
					<x>0.45</x>
					<y>0.48</y>
					<L>24</L>
				</xyL>
			</cie>
			<srgb>
				<red>158</red>
				<green>133</green>
				<blue>2</blue>
			</srgb>
		</item>
		<item token="PLRTE">
			<cie>
				<xyL>
					<x>0.58</x>
					<y>0.35</y>
					<L>8</L>
				</xyL>
			</cie>
			<srgb>
				<red>149</red>
				<green>41</green>
				<blue>22</blue>
			</srgb>
		</item>
		<item token="DEPCN" transparency="1.0">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.31</y>
					<L>10</L>
				</xyL>
			</cie>
			<srgb>
				<red>76</red>
				<green>91</green>
				<blue>99</blue>
			</srgb>
		</item>
	</palette>
	<palette name="Night" css="nightSvgStyle.css">
		<item token="ORG">
			<cie>
				<xyL>
					<x>0.5</x>
					<y>0.4</y>
					<L>1.25</L>
				</xyL>
			</cie>
			<srgb>
				<red>48</red>
				<green>23</green>
				<blue>5</blue>
			</srgb>
		</item>
		<item token="RED">
			<cie>
				<xyL>
					<x>0.48</x>
					<y>0.3</y>
					<L>1.25</L>
				</xyL>
			</cie>
			<srgb>
				<red>57</red>
				<green>14</green>
				<blue>22</blue>
			</srgb>
		</item>
		<item token="BLK">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.31</y>
					<L>2.5</L>
				</xyL>
			</cie>
			<srgb>
				<red>37</red>
				<green>45</green>
				<blue>49</blue>
			</srgb>
		</item>
		<item token="WHITE">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.31</y>
					<L>5</L>
				</xyL>
			</cie>
			<srgb>
				<red>54</red>
				<green>65</green>
				<blue>71</blue>
			</srgb>
		</item>
		<item token="CHMGD">
			<cie>
				<xyL>
					<x>0.3</x>
					<y>0.17</y>
					<L>2</L>
				</xyL>
			</cie>
			<srgb>
				<red>65</red>
				<green>18</green>
				<blue>71</blue>
			</srgb>
		</item>
		<item token="SNDG2">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.31</y>
					<L>5</L>
				</xyL>
			</cie>
			<srgb>
				<red>54</red>
				<green>65</green>
				<blue>71</blue>
			</srgb>
		</item>
		<item token="GOLDN">
			<cie>
				<xyL>
					<x>0.45</x>
					<y>0.48</y>
					<L>3</L>
				</xyL>
			</cie>
			<srgb>
				<red>58</red>
				<green>48</green>
				<blue>0</blue>
			</srgb>
		</item>
		<item token="PLRTE">
			<cie>
				<xyL>
					<x>0.58</x>
					<y>0.35</y>
					<L>0.9</L>
				</xyL>
			</cie>
			<srgb>
				<red>51</red>
				<green>8</green>
				<blue>3</blue>
			</srgb>
		</item>
		<item token="DEPCN">
			<cie>
				<xyL>
					<x>0.28</x>
					<y>0.31</y>
					<L>1.25</L>
				</xyL>
			</cie>
			<srgb>
				<red>24</red>
				<green>30</green>
				<blue>33</blue>
			</srgb>
		</item>
	</palette>
</cp:colorProfile>

=== S-100ExpertTeam/OpenS100/ProgramData/PC/S128_Portrayal/ColorProfiles/colorProfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<cp:colorProfile xmlns:cp="http://www.iho.int/S100ColorProfile/5.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.iho.int/S100ColorProfile/5.1 https://schemas.s100dev.net/schemas/S100/5.1.0/S100PC/20230327/S100ColorProfile.xsd">
    <colors>
        <color token="CHGRN" name="green">
            <description>Chart green</description>
        </color>
        <color token="CHYLW" name="yellow">
            <description>Chart yellow</description>
        </color>
        <color token="CHMGD" name="magenta">
            <description>Chart magenta dominant</description>
        </color>
    </colors>
  <palette name="Day" css="daySvgStyle.css">
    <item token="CHGRN">
      <cie>
        <xyL>
          <x>0.31</x>
          <y>0.56</y>
          <L>60</L>
        </xyL>
      </cie>
      <srgb>
        <red>82</red>
        <green>232</green>
        <blue>59</blue>
      </srgb>
    </item>
    <item token="CHYLW">
      <cie>
        <xyL>
          <x>0.41</x>
          <y>0.49</y>
          <L>70</L>
        </xyL>
      </cie>
      <srgb>
        <red>225</red>
        <green>225</green>
        <blue>57</blue>
      </srgb>
    </item>
    <item token="CHMGD">
      <cie>
        <xyL>
          <x>0.3</x>
          <y>0.17</y>
          <L>20</L>
        </xyL>
      </cie>
      <srgb>
        <red>192</red>
        <green>69</green>
        <blue>209</blue>
      </srgb>
    </item>
  </palette>
  <palette name="Dusk" css="duskSvgStyle.css">
	<item token="CHGRN">
      <cie>
        <xyL>
          <x>0.31</x>
          <y>0.56</y>
          <L>20</L>
        </xyL>
      </cie>
      <srgb>
        <red>47</red>
        <green>142</green>
        <blue>32</blue>
      </srgb>
    </item>
    <item token="CHYLW">
      <cie>
        <xyL>
          <x>0.41</x>
          <y>0.49</y>
          <L>24</L>
        </xyL>
      </cie>
      <srgb>
        <red>139</red>
        <green>139</green>
        <blue>31</blue>
      </srgb>
    </item>
    <item token="CHMGD">
      <cie>
        <xyL>
          <x>0.28</x>
          <y>0.24</y>
          <L>18</L>
        </xyL>
      </cie>
      <srgb>
        <red>130</red>
        <green>108</green>
        <blue>161</blue>
      </srgb>
    </item>
  </palette>	
  <palette name="Night" css="nightSvgStyle.css">
    <item token="CHGRN">
      <cie>
        <xyL>
          <x>0.31</x>
          <y>0.56</y>
          <L>2.5</L>
        </xyL>
      </cie>
      <srgb>
        <red>12</red>
        <green>52</green>
        <blue>6</blue>
      </srgb>
    </item>
    <item token="CHYLW">
      <cie>
        <xyL>
          <x>0.41</x>
          <y>0.49</y>
          <L>3</L>
        </xyL>
      </cie>
      <srgb>
        <red>50</red>
        <green>50</green>
        <blue>6</blue>
      </srgb>
    </item>
    <item token="CHMGD">
      <cie>
        <xyL>
          <x>0.3</x>
          <y>0.17</y>
          <L>2</L>
        </xyL>
      </cie>
      <srgb>
        <red>65</red>
        <green>18</green>
        <blue>71</blue>
      </srgb>
    </item>	
  </palette>
</cp:colorProfile>
