=== S-100ExpertTeam/OpenS100/ProgramData/PC/S421_Portrayal/S100PortrayalCatalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- S-100 Portrayal catalog schema
      Build 20181015 Updated for post-TSM6 finalization of Part 15 (2018-10-24)
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:s100Symbol="http://www.iho.int/S100SymbolDefinition" version="4.0.0-20181015">
	<xs:import namespace="http://www.iho.int/S100SymbolDefinition" schemaLocation="S100SymbolDefinition.xsd"/>
	<!-- Supported type for context parameters -->
	<xs:simpleType name="ParameterType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Boolean"/>
			<xs:enumeration value="Integer"/>
			<xs:enumeration value="Double"/>
			<xs:enumeration value="String"/>
			<xs:enumeration value="Date"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- The type of an external file -->
	<xs:simpleType name="FileType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Font"/>
			<xs:enumeration value="AreaFill"/>
			<xs:enumeration value="LineStyle"/>
			<xs:enumeration value="Symbol"/>
			<xs:enumeration value="ColorProfile"/>
			<xs:enumeration value="Pixmap"/>
			<xs:enumeration value="Rule"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- The format of an external file -->
	<xs:simpleType name="FileFormat">
		<xs:restriction base="xs:string">
			<xs:enumeration value="XML"/>
			<xs:enumeration value="SVG"/>
			<xs:enumeration value="XSLT"/>
			<xs:enumeration value="TTF"/>
			<xs:enumeration value="LUA"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- The type of an template -->
	<xs:simpleType name="RuleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TopLevelTemplate"/>
			<xs:enumeration value="SubTemplate"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Class for descriptive information about a catalogue item -->
	<xs:complexType name="Description">
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="language" type="xs:language"/>
		</xs:sequence>
	</xs:complexType>
	<!-- Abstract base class for catalogue items -->
	<xs:complexType name="CatalogItem" abstract="true">
		<xs:sequence>
			<xs:element name="description" type="Description" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="s100Symbol:IdString" use="required"/>
	</xs:complexType>
	<!-- catalogue item for an external file -->
	<xs:complexType name="ExternalFile">
		<xs:complexContent>
			<xs:extension base="CatalogItem">
				<xs:sequence>
					<xs:element name="fileName" type="xs:anyURI"/>
					<xs:element name="fileType" type="FileType"/>
					<xs:element name="fileFormat" type="FileFormat"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- catalogue item for an XSLT rule file -->
	<xs:complexType name="RuleFile">
		<xs:complexContent>
			<xs:extension base="ExternalFile">
				<xs:sequence>
					<xs:element name="ruleType" type="RuleType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Class for a viewing group -->
	<xs:complexType name="ViewingGroup">
		<xs:complexContent>
			<xs:extension base="CatalogItem"/>
		</xs:complexContent>
	</xs:complexType>
	<!-- Class for a viewing group layer (an aggregation of viewing groups) -->
	<xs:complexType name="ViewingGroupLayer">
		<xs:complexContent>
			<xs:extension base="CatalogItem">
				<xs:sequence>
					<xs:element name="viewingGroup" type="s100Symbol:IdString" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Class for a display mode (an aggregation of  viewing group layers) -->
	<xs:complexType name="DisplayMode">
		<xs:complexContent>
			<xs:extension base="CatalogItem">
				<xs:sequence>
					<xs:element name="viewingGroupLayer" type="s100Symbol:IdString" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Class for a display plane -->
	<xs:complexType name="DisplayPlane">
		<xs:complexContent>
			<xs:extension base="CatalogItem"/>
		</xs:complexContent>
	</xs:complexType>
	<!-- Class for a context parameter -->
	<xs:complexType name="ContextParameter">
		<xs:complexContent>
			<xs:extension base="CatalogItem">
				<xs:sequence>
					<xs:element name="type" type="ParameterType"/>
					<xs:element name="default" type="xs:anyType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Pixmaps">
		<xs:sequence>
			<xs:element name="pixmap" type="ExternalFile" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ColorProfiles">
		<xs:sequence>
			<xs:element name="colorProfile" type="ExternalFile" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Symbols">
		<xs:sequence>
			<xs:element name="symbol" type="ExternalFile" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LineStyles">
		<xs:sequence>
			<xs:element name="lineStyle" type="ExternalFile" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AreaFills">
		<xs:sequence>
			<xs:element name="areaFill" type="ExternalFile" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Fonts">
		<xs:sequence>
			<xs:element name="font" type="ExternalFile" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ViewingGroups">
		<xs:sequence>
			<xs:element name="viewingGroup" type="ViewingGroup" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ViewingGroupLayers">
		<xs:sequence>
			<xs:element name="viewingGroupLayer" type="ViewingGroupLayer" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DisplayModes">
		<xs:sequence>
			<xs:element name="displayMode" type="DisplayMode" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DisplayPlanes">
		<xs:sequence>
			<xs:element name="displayPlane" type="DisplayPlane" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Context">
		<xs:sequence>
			<xs:element name="parameter" type="ContextParameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Rules">
		<xs:sequence>
			<xs:element name="ruleFile" type="RuleFile" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PortrayalCatalog">
		<xs:sequence>
			<xs:element name="pixmaps" type="Pixmaps">
				<xs:key name="pixmapKey">
					<xs:selector xpath="pixmap"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
			<xs:element name="colorProfiles" type="ColorProfiles">
				<xs:key name="colorProfileKey">
					<xs:selector xpath="colorProfile"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
			<xs:element name="symbols" type="Symbols">
				<xs:key name="symbolKey">
					<xs:selector xpath="symbol"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
			<xs:element name="lineStyles" type="LineStyles">
				<xs:key name="lineStyleKey">
					<xs:selector xpath="lineStyle"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
			<xs:element name="areaFills" type="AreaFills">
				<xs:key name="areaFillKey">
					<xs:selector xpath="areaFill"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
			<xs:element name="fonts" type="Fonts">
				<xs:key name="fontKey">
					<xs:selector xpath="font"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
			<xs:element name="viewingGroups" type="ViewingGroups">
				<xs:key name="viewingGroupKey">
					<xs:selector xpath="viewingGroup"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
			<xs:element name="foundationMode">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="viewingGroup" type="s100Symbol:IdString" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="viewingGroupLayers" type="ViewingGroupLayers">
				<xs:key name="viewingGroupLayerKey">
					<xs:selector xpath="viewingGroupLayer"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
			<xs:element name="displayModes" type="DisplayModes">
				<xs:key name="displayModeKey">
					<xs:selector xpath="displayMode"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
			<xs:element name="displayPlane" type="DisplayPlanes">
				<xs:key name="displayPlaneKey">
					<xs:selector xpath="displayPlane"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
			<xs:element name="context" type="Context">
				<xs:key name="contextKey">
					<xs:selector xpath="parameter"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
			<xs:element name="rules" type="Rules">
				<xs:key name="ruleKey">
					<xs:selector xpath="ruleFile"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="productId" type="xs:string" use="required"/>
		<xs:attribute name="version" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- THE ROOT ELEMENT -->
	<xs:element name="portrayalCatalog" type="PortrayalCatalog">
		<!-- KEYREF FOR VIEWING GROUPS -->
		<xs:keyref name="viewingGroupRef" refer="viewingGroupKey">
			<xs:selector xpath="viewingGroupLayers/viewingGroupLayer/viewingGroup|foundationMode/viewingGroup"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<!-- KEYREF FOR VIEWING GROUP LAYERS -->
		<xs:keyref name="viewingGroupLayerRef" refer="viewingGroupLayerKey">
			<xs:selector xpath="displayModes/displayMode/viewingGroupLayer"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
</xs:schema>

=== S-100ExpertTeam/OpenS100/ProgramData/PC/S111_Portrayal/portrayal_catalogue.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- 
  Version 2.0.0 Build 20240801 Update of the S-111 Edition 1.0.0 PC for S-111 Edition 2.0.0
    Updated by Raphael Malyankar (Portolan Sciences LLC)
-->
<pc:portrayalCatalog xmlns:pc="http://www.iho.int/S100PortrayalCatalog/5.2"
  xmlns:xsl="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  productId="S-111"
  version="2.0.0"
  xsi:schemaLocation="http://www.iho.int/S100PortrayalCatalog/5.2 https://schemas.s100dev.net/schemas/S100/5.2.0/S100PC/20240415/S100PortrayalCatalog.xsd">
  <pixmaps/>
  <colorProfiles>
    <colorProfile id="1">
      <description>
        <name>Color Profile for S-111</name>
        <description>Color profile for S-111 with day, dusk, and night color palettes</description>
        <language>eng</language>
      </description>
      <fileName>colorProfile.xml</fileName>
      <fileType>ColorProfile</fileType>
      <fileFormat>XML</fileFormat>
    </colorProfile>
  </colorProfiles>
  <symbols>
    <symbol id="SCAROW01">
      <description>
        <name>SCAROW01</name>
        <description>Surface Current Vector Band 1</description>
        <language>eng</language>
      </description>
      <fileName>SCAROW01.svg</fileName>
      <fileType>Symbol</fileType>
      <fileFormat>SVG</fileFormat>
    </symbol>
    <symbol id="SCAROW02">
      <description>
        <name>SCAROW02</name>
        <description>Surface Current Vector Band 2</description>
        <language>eng</language>
      </description>
      <fileName>SCAROW02.svg</fileName>
      <fileType>Symbol</fileType>
      <fileFormat>SVG</fileFormat>
    </symbol>
    <symbol id="SCAROW03">
      <description>
        <name>SCAROW03</name>
        <description>Surface Current Vector Band 3</description>
        <language>eng</language>
      </description>
      <fileName>SCAROW03.svg</fileName>
      <fileType>Symbol</fileType>
      <fileFormat>SVG</fileFormat>
    </symbol>
    <symbol id="SCAROW04">
      <description>
        <name>SCAROW04</name>
        <description>Surface Current Vector Band 4</description>
        <language>eng</language>
      </description>
      <fileName>SCAROW04.svg</fileName>
      <fileType>Symbol</fileType>
      <fileFormat>SVG</fileFormat>
    </symbol>
    <symbol id="SCAROW05">
      <description>
        <name>SCAROW05</name>
        <description>Surface Current Vector Band 5</description>
        <language>eng</language>
      </description>
      <fileName>SCAROW05.svg</fileName>
      <fileType>Symbol</fileType>
      <fileFormat>SVG</fileFormat>
    </symbol>
    <symbol id="SCAROW06">
      <description>
        <name>SCAROW06</name>
        <description>Surface Current Vector Band 6</description>
        <language>eng</language>
      </description>
      <fileName>SCAROW06.svg</fileName>
      <fileType>Symbol</fileType>
      <fileFormat>SVG</fileFormat>
    </symbol>
    <symbol id="SCAROW07">
      <description>
        <name>SCAROW07</name>
        <description>Surface Current Vector Band 7</description>
        <language>eng</language>
      </description>
      <fileName>SCAROW07.svg</fileName>
      <fileType>Symbol</fileType>
      <fileFormat>SVG</fileFormat>
    </symbol>
    <symbol id="SCAROW08">
      <description>
        <name>SCAROW08</name>
        <description>Surface Current Vector Band 8</description>
        <language>eng</language>
      </description>
      <fileName>SCAROW08.svg</fileName>
      <fileType>Symbol</fileType>
      <fileFormat>SVG</fileFormat>
    </symbol>
    <symbol id="SCAROW09">
      <description>
        <name>SCAROW09</name>
        <description>Surface Current Vector Band 9</description>
        <language>eng</language>
      </description>
      <fileName>SCAROW09.svg</fileName>
      <fileType>Symbol</fileType>
      <fileFormat>SVG</fileFormat>
    </symbol>
  </symbols>
  <styleSheets>
    <styleSheet id="S111Day">
      <fileName>SVGStyle_S111day.css</fileName>
      <fileType>StyleSheet</fileType>
      <fileFormat>CSS</fileFormat>
    </styleSheet>
    <styleSheet id="S111Night">
      <fileName>SVGStyle_S111night.css</fileName>
      <fileType>StyleSheet</fileType>
      <fileFormat>CSS</fileFormat>
    </styleSheet>
    <styleSheet id="S111Dusk">
      <fileName>SVGStyle_S111dusk.css</fileName>
      <fileType>StyleSheet</fileType>
      <fileFormat>CSS</fileFormat>
    </styleSheet>
  </styleSheets>
  <lineStyles/>
  <areaFills/>
  <fonts/>
  <viewingGroups>
    <viewingGroup id="33060">
      <description>
        <name>current and tidal stream information (CURENT, TS_FEB, TS_PAD, TS_PNH, TS_PRH, TS_TIS)</name>
        <description>Other: H, I - Depths, Currents, etc.</description>
        <language>eng</language>
      </description>
    </viewingGroup>
  </viewingGroups>
  <foundationMode/>
  <viewingGroupLayers>
    <viewingGroupLayer id="17">
      <description>
        <name>Tidal</name>
        <description>Other Display elements</description>
        <language>eng</language>
      </description>
      <viewingGroup>33060</viewingGroup>
    </viewingGroupLayer>
  </viewingGroupLayers>
  <displayModes>
    <displayMode id="DisplayBase">
      <description>
        <name>Display Base</name>
        <description>Always on display</description>
        <language>eng</language>
      </description>
    </displayMode>
    <displayMode id="StandardDisplay">
      <description>
        <name>Standard Display</name>
        <description>ECDIS default display</description>
        <language>eng</language>
      </description>
    </displayMode>
    <displayMode id="OtherInformation">
      <description>
        <name>Other Information</name>
        <description>All other objects in the SENC</description>
        <language>eng</language>
      </description>
      <viewingGroupLayer>17</viewingGroupLayer>
    </displayMode>  
  </displayModes>
  <displayPlanes>
    <displayPlane id="OverRadar" order="1">
      <description>
        <name>Over radar</name>
        <description>Content displayed on top of Radar image</description>
        <language>eng</language>
      </description>
    </displayPlane>
    <displayPlane id="UnderRadar" order="-1">
      <description>
        <name>Under radar</name>
        <description>Content displayed underneath Radar image</description>
        <language>eng</language>
      </description>
    </displayPlane>
  </displayPlanes>
  <context/>
  <rules>
  	<ruleFile id="1">
	 <description>
		<name>main</name>
		<description>main</description>
		<language>eng</language>
	 </description>
	 <fileName>main.xsl</fileName>
	 <fileType>Rule</fileType>
	 <fileFormat>XSLT</fileFormat>
	 <ruleType>TopLevelTemplate</ruleType>
  </ruleFile>  
    <ruleFile id="2">
      <description>
        <name>SurfaceCurrent</name>
        <description>Surface Current</description>
        <language>eng</language>
      </description>
      <fileName>SurfaceCurrent.xsl</fileName>
      <fileType>Rule</fileType>
      <fileFormat>XSLT</fileFormat>
      <ruleType>SubTemplate</ruleType>
    </ruleFile>
    <ruleFile id="3">
      <description>
        <name>select_arrow</name>
        <description>Surface Current</description>
        <language>eng</language>
      </description>
      <fileName>select_arrow.xsl</fileName>
      <fileType>Rule</fileType>
      <fileFormat>XSLT</fileFormat>
      <ruleType>SubTemplate</ruleType>
    </ruleFile>
  </rules>
</pc:portrayalCatalog>
